### ISSUE TITLE
SeisFlows Version 3.0.0 To Do

### ISSUE THREAD

**Issue by bch0w** [adjtomo/seisflows#159]
In the next major version of SeisFlows, we would like to expand features and usability of the code.

- [ ] Large, single job system module #118 
- [ ] Pre-commit framework #120 
- [ ] Finish WIP documentation #121 
- [ ] Improve checkpoint/state system in #144 
- [ ] Improve check system in #142

**Comment by bch0w** [comment]
Closed because this is what milestones are for
